"""Initial: documents, document_parses, jobs with relationships

Revision ID: 93cb55e5f71b
Revises: 
Create Date: 2026-05-26 14:29:00.330441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93cb55e5f71b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('doc_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.Enum('ORIGINALS', 'PARSES', 'ARTIFACTS', name='category'), nullable=False),
    sa.Column('status', sa.Enum('DONE', 'FAILED', 'PROCESSING', 'PENDING', 'STORED', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('document_parses',
    sa.Column('parse_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.BigInteger(), nullable=False),
    sa.Column('representation_type', sa.String(length=50), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parse_id')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.BigInteger(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DONE', 'FAILED', 'PROCESSING', 'PENDING', 'STORED', name='status'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('document_parses')
    op.drop_table('documents')
    # ### end Alembic commands ###
